### ISSUE TITLE
Revisit performance

### ISSUE THREAD

**Issue by Gabriella439** [coralogix/dhall-concourse#4]
Do you have an example expression that I could use for benchmarking?  I believe performance has improved substantially since this repository went dormant, but I currently don't have an example Concourse Dhall configuration file I can use to verify that.

All I have verified so far is that the Haskell implementation can interpret `types/package.dhall` in a few seconds:

```
$ time dhall hash --file ~/proj/dhall-concourse/types/package.dhall 
sha256:f45ad5ca29b957eb028b3d7bbb24da2e63ec79cbab5c2042292f7178ec08c6d5

real	0m5.256s
user	0m4.831s
sys	0m0.299s
```

**Comment by ari-becker** [comment]
> 
> 
> Do you have an example expression that I could use for benchmarking? I believe performance has improved substantially since this repository went dormant, but I currently don't have an example Concourse Dhall configuration file I can use to verify that.
> 
> All I have verified so far is that the Haskell implementation can interpret `types/package.dhall` in a few seconds:
> 
> ```
> $ time dhall hash --file ~/proj/dhall-concourse/types/package.dhall 
> sha256:f45ad5ca29b957eb028b3d7bbb24da2e63ec79cbab5c2042292f7178ec08c6d5
> 
> real	0m5.256s
> user	0m4.831s
> sys	0m0.299s
> ```

Sorry, nothing we can make public as of yet.

We do want to come back to `dhall-concourse` at some point, as our pipelines are currently not type-checked in Dhall and schema enforcement is handled by `fly` at runtime, which is not ideal. But we're also currently not bottlenecked by this - our pipelines are pretty stable for now. 

If we were to come back to `dhall-concourse`, I think we'd have to put in some significant thought into how to support a plugin architecture for Concourse resources, so that additional Concourse resource types can be added to the Dhall types as needed. Having a variable number of options under the unions would, of course, negatively affect performance as more Concourse resource types were added, but it remains to be seen whether that would be a real-world impediment directing us to untyped JSON for all Concourse resource types.

**Comment by ari-becker** [comment]
Realized that I should have closed this as stale, since the re-architecture of this repository, which is now much more performant.
